### PR TITLE
WIP: reconnect connections after errors

### LINKED ISSUE #92: Recreate Connection object when there are errors
In cases when there's a protocol error, we cannot use the underlying connection anymore because some bytes may be left out in the underlying connection. For the client to automatically recover from these class of errors, we should recreate a connection before we send the next request.

We need not do this for all errors. Only some types of errors like `IOError`, `ClientError`(except `KeyTooLong`), `ServerError`. We need not do this for `CommandError`s.

@aisk What do you think about this?

### PR DESCRIPTION
**Pull request by letmutx**
Fixes #92

### CODE REVIEW

**Comment by aisk** [comment]
Hi @letmutx sorry I forgot that we had a r2d2 wrapper for this crate: https://github.com/megumish/r2d2-memcache

So I think we should consider that to expose this crate's status like connection failed, and let r2d2-memcache to handle some retry work? Just a quick thought and may be invalid, what do you think?

**Comment by letmutx** [comment]
Yep, that seems to be a better idea.

**Comment by aisk** [comment]
Sorry I had made some misleading, I think the retry mechanism is also needed in memcache crate, someone may be using this crate alone, and I think the work in this PR should be continue.

**Comment by letmutx** [comment]
I think it's fair enough for to ask people to use r2d2 when they need that feature. We should document that somewhere, though.

**Comment by letmutx** [comment]
Adding in #108

**Pull request closed without merging**
