### PR TITLE
Multiple Server Support

### LINKED ISSUE #6: Support multiple servers
By now the project supports just one server. It is recommended by the memcached project site that clients can hash servers and keys so things go to right location.

### PR DESCRIPTION
**Pull request by paulosuzart**
Should be able to close #6. Open for your considerations and concerns. Seems to be fine.

Bests

### CODE REVIEW

**Comment by paulosuzart** [comment]
Travis is failing because it now needs memcached in at least two memcache instances.

**Comment by paulosuzart** [comment]
No idea why these two tests are failing. They all pass over here.

**Comment by aisk** [comment]
I think we have some concurrency bug. I don't know is cargo running all test in multiple process. Maybe we should use `cargo test -j1`.

**Comment by paulosuzart** [comment]
I've noticed. The whole code is not thread safe. So the user of the lib
should take care of the client/connection object.

The same happens for rusqlite lib.

But I suspect cargo is running concurrently.

**Comment by paulosuzart** [comment]
Don't know what happens. Tried in j1 and j5, etc all works. Can you clone this code and take a look?

**Comment by aisk** [comment]
I run the test on my machine, but it always failed. I think maybe it's not caused by the concurrency problem, maybe there're some logic bug in our code.

**Comment by paulosuzart** [comment]
Ok, I'll try another machine. My laptop always passes. In 10 hours I'll tell what I find.
Cheers!

**Comment by paulosuzart** [comment]
Just increased the expiration time in the set command. Now passes. I think memcached was killing our entry before it get accessed back in the tests.

**Comment by aisk** [comment]
Cool, test is passed in most time XD

**Comment by paulosuzart** [comment]
This is crazy because 0 expiration was supposed to be no expiration according to this: https://github.com/memcached/memcached/blob/master/doc/protocol.txt#L163 I'll continue to keep an eye an make different tests to catch anything wrong.

**Pull request merged**
